# Generated by Django 3.2.5 on 2021-08-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbsApp', '0002_bbs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=500)),
                ('writer', models.CharField(max_length=100)),
                ('board_id', models.IntegerField()),
            ],
        ),
    ]
