# Generated by Django 3.2.5 on 2021-08-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='ChoiceTbl',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionTbl',
        ),
    ]
